import type { Locale } from "./i18n";

const replacements: Record<Locale, Array<[string, string]>> = {
  en: [],
  zh: [
    ["source-to-pay", "寻源到付款"],
    ["Source-to-Pay", "寻源到付款"],
    ["4-way invoice matching", "四方发票匹配"],
    ["4-Way Invoice Matching", "四方发票匹配"],
    ["4-way matching", "四方匹配"],
    ["AI negotiation", "人工智能谈判"],
    ["AI Negotiation", "人工智能谈判"],
    ["AI-powered", "人工智能驱动"],
    ["AI 驱动", "人工智能驱动"],
    ["AI 谈判", "人工智能谈判"],
    ["Inquiry-to-Quote", "询价到报价"],
    ["Inquiry to Quote", "询价到报价"],
    ["Requisitions-to-PO", "请购到采购订单"],
    ["Requisition-to-PO", "请购到采购订单"],
    ["Requisition to PO", "请购到采购订单"],
    ["Invoice-to-Pay", "发票到付款"],
    ["Invoice to Pay", "发票到付款"],
    ["landed cost", "到岸成本"],
    ["Landed Cost", "到岸成本"],
    ["BOM costing", "BOM 成本核算"],
    ["BOM Costing", "BOM 成本核算"],
    ["purchase order", "采购订单"],
    ["Purchase Order", "采购订单"],
  ],
  es: [
    ["source-to-pay", "source-to-pay (abastecimiento a pago)"],
    ["Source-to-Pay", "Source-to-Pay (abastecimiento a pago)"],
    ["4-way invoice matching", "conciliación de facturas de 4 vías"],
    ["4-Way Invoice Matching", "Conciliación de facturas de 4 vías"],
    ["4-way matching", "conciliación de 4 vías"],
    ["AI negotiation", "negociación con IA"],
    ["AI Negotiation", "Negociación con IA"],
    ["Inquiry-to-Quote", "consulta a cotización"],
    ["Requisitions-to-PO", "requisición a orden de compra"],
    ["Requisition-to-PO", "requisición a orden de compra"],
    ["Invoice-to-Pay", "factura a pago"],
    ["landed cost", "costo total puesto en destino"],
    ["Landed Cost", "Costo total puesto en destino"],
    ["BOM costing", "costeo de BOM"],
  ],
  ja: [
    ["source-to-pay", "ソーシングから支払いまで"],
    ["Source-to-Pay", "ソーシングから支払いまで"],
    ["4-way invoice matching", "4点請求書照合"],
    ["4-Way Invoice Matching", "4点請求書照合"],
    ["4-way matching", "4点照合"],
    ["AI negotiation", "AI交渉"],
    ["AI Negotiation", "AI交渉"],
    ["Inquiry-to-Quote", "問い合わせから見積まで"],
    ["Requisitions-to-PO", "購買依頼から発注まで"],
    ["Requisition-to-PO", "購買依頼から発注まで"],
    ["Invoice-to-Pay", "請求書から支払いまで"],
    ["landed cost", "着地原価"],
    ["Landed Cost", "着地原価"],
    ["BOM costing", "BOM原価計算"],
  ],
  de: [
    ["source-to-pay", "Source-to-Pay"],
    ["4-way invoice matching", "4-Wege-Rechnungsabgleich"],
    ["4-Way Invoice Matching", "4-Wege-Rechnungsabgleich"],
    ["4-way matching", "4-Wege-Abgleich"],
    ["AI negotiation", "KI-Verhandlung"],
    ["AI Negotiation", "KI-Verhandlung"],
    ["Inquiry-to-Quote", "Anfrage bis Angebot"],
    ["Requisitions-to-PO", "Bedarfsanforderung bis Bestellung"],
    ["Requisition-to-PO", "Bedarfsanforderung bis Bestellung"],
    ["Invoice-to-Pay", "Rechnung bis Zahlung"],
    ["landed cost", "Einstandskosten"],
    ["Landed Cost", "Einstandskosten"],
    ["BOM costing", "Stücklistenkalkulation"],
  ],
  fr: [
    ["source-to-pay", "source-to-pay (du sourcing au paiement)"],
    ["Source-to-Pay", "Source-to-Pay (du sourcing au paiement)"],
    ["4-way invoice matching", "rapprochement de facture à 4 niveaux"],
    ["4-Way Invoice Matching", "Rapprochement de facture à 4 niveaux"],
    ["4-way matching", "rapprochement à 4 niveaux"],
    ["AI negotiation", "négociation par IA"],
    ["AI Negotiation", "Négociation par IA"],
    ["Inquiry-to-Quote", "demande à devis"],
    ["Requisitions-to-PO", "demande d'achat à bon de commande"],
    ["Requisition-to-PO", "demande d'achat à bon de commande"],
    ["Invoice-to-Pay", "facture à paiement"],
    ["landed cost", "coût rendu"],
    ["Landed Cost", "Coût rendu"],
    ["BOM costing", "calcul de coût BOM"],
  ],
  ko: [
    ["source-to-pay", "소싱부터 결제까지"],
    ["Source-to-Pay", "소싱부터 결제까지"],
    ["4-way invoice matching", "4자 송장 매칭"],
    ["4-Way Invoice Matching", "4자 송장 매칭"],
    ["4-way matching", "4자 매칭"],
    ["AI negotiation", "AI 협상"],
    ["AI Negotiation", "AI 협상"],
    ["Inquiry-to-Quote", "문의에서 견적까지"],
    ["Requisitions-to-PO", "구매요청에서 발주까지"],
    ["Requisition-to-PO", "구매요청에서 발주까지"],
    ["Invoice-to-Pay", "송장에서 결제까지"],
    ["landed cost", "도착 원가"],
    ["Landed Cost", "도착 원가"],
    ["BOM costing", "BOM 원가 계산"],
  ],
  pt: [
    ["source-to-pay", "source-to-pay (da origem ao pagamento)"],
    ["Source-to-Pay", "Source-to-Pay (da origem ao pagamento)"],
    ["4-way invoice matching", "conciliação de faturas em 4 vias"],
    ["4-Way Invoice Matching", "Conciliação de faturas em 4 vias"],
    ["4-way matching", "conciliação em 4 vias"],
    ["AI negotiation", "negociação com IA"],
    ["AI Negotiation", "Negociação com IA"],
    ["Inquiry-to-Quote", "consulta à cotação"],
    ["Requisitions-to-PO", "requisição ao pedido de compra"],
    ["Requisition-to-PO", "requisição ao pedido de compra"],
    ["Invoice-to-Pay", "fatura ao pagamento"],
    ["landed cost", "custo total de chegada"],
    ["Landed Cost", "Custo total de chegada"],
    ["BOM costing", "custeio de BOM"],
  ],
  it: [
    ["source-to-pay", "source-to-pay (dal sourcing al pagamento)"],
    ["Source-to-Pay", "Source-to-Pay (dal sourcing al pagamento)"],
    ["4-way invoice matching", "matching fatture a 4 vie"],
    ["4-Way Invoice Matching", "Matching fatture a 4 vie"],
    ["4-way matching", "matching a 4 vie"],
    ["AI negotiation", "negoziazione con IA"],
    ["AI Negotiation", "Negoziazione con IA"],
    ["Inquiry-to-Quote", "richiesta a preventivo"],
    ["Requisitions-to-PO", "richiesta d'acquisto a ordine"],
    ["Requisition-to-PO", "richiesta d'acquisto a ordine"],
    ["Invoice-to-Pay", "fattura a pagamento"],
    ["landed cost", "costo landed"],
    ["Landed Cost", "Costo landed"],
    ["BOM costing", "costing BOM"],
  ],
  ar: [
    ["source-to-pay", "من التوريد إلى الدفع"],
    ["Source-to-Pay", "من التوريد إلى الدفع"],
    ["4-way invoice matching", "مطابقة الفواتير رباعية الأطراف"],
    ["4-Way Invoice Matching", "مطابقة الفواتير رباعية الأطراف"],
    ["4-way matching", "مطابقة رباعية الأطراف"],
    ["AI negotiation", "التفاوض بالذكاء الاصطناعي"],
    ["AI Negotiation", "التفاوض بالذكاء الاصطناعي"],
    ["Inquiry-to-Quote", "من الاستفسار إلى عرض السعر"],
    ["Requisitions-to-PO", "من طلب الشراء إلى أمر الشراء"],
    ["Requisition-to-PO", "من طلب الشراء إلى أمر الشراء"],
    ["Invoice-to-Pay", "من الفاتورة إلى الدفع"],
    ["landed cost", "التكلفة النهائية للوصول"],
    ["Landed Cost", "التكلفة النهائية للوصول"],
    ["BOM costing", "حساب تكلفة قائمة المواد"],
  ],
};

export function localizeTerminology(value: string, locale: Locale) {
  return replacements[locale].reduce(
    (output, [source, replacement]) => output.split(source).join(replacement),
    value,
  );
}
